### PR TITLE
Change from Spray to Akka HTTP to allow for usage of current Akka version

### PR DESCRIPTION
**Pull request by PhilAndrew**
You will need to manually fix build.sbt as I'm not sure how to build this, the important part being RestService.scala

### CODE REVIEW

**Comment by cornerman** [comment]
Hi and thank you for the contribution :)

The build.sbt looks fine, it compiles and the tests pass. I have updated our travis config: If you rebase on the current master and push again, it should also work on travis. I will have a closer at look at the code later!

**Comment by cornerman** [comment]
Thanks for porting this, code looks good to me! I agree with your notes about non-blocking, which we should definitely do. For the deserialization error, it would be good to have something there, do you have an idea? :)

For testing, we run the unit tests (sbt test) and the integration tests which need a running neo4j instance on localhost (sbt it:test).

The integration tests currently do not compile, where it is still using a spray import for BasicHttpCredentials ([IntegrationSpecification.scala#L7](https://github.com/renesca/renesca/blob/master/jvm/src/it/scala/renesca/IntegrationSpecification.scala#L7)). Maybe even better not to leak the implementation in the RestService constructor, but to have our own credentials container. Can you fix this?

**Comment by PhilAndrew** [comment]
I'll get back to this in a few days, just busy something.

**Comment by fdietze** [comment]
We could just pass Futures through the whole code, to get rid of blocking. This would also allow to encode the parsing error in a failed Future.

**Comment by cornerman** [comment]
I agree that this is what we want to do in the end. But this does not necessarily need to be within the scope of this PR.

**Comment by PhilAndrew** [comment]
I added futures to my hacking fork but not yet checked if its correct, I'll submit a PR later.

**Comment by PhilAndrew** [comment]
The test failure says it failed in Java 7, also I note that Akka 2.4 requires Java 8.

http://stackoverflow.com/questions/32959187/akka-hello-world-problems-unsupported-major-minor-version-52-0

http://akka.io/news/2015/09/30/akka-2.4.0-released.html
"dropped support for Java 6 & 7 as announced in the last roadmap update, and now require Java 8 or later"

So I would say, if your OK with going to Java 8 and leaving Java 7 behind then this is fine.

**Comment by fdietze** [comment]
Thank you very much!

**Pull request merged**
